version: '3.1'

services:
  app:
    build: ./
    volumes: 
        - ./src/:/app/src
  #db:
  #  image: mysql
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: noEsSeguroCambiame
  #  volumes:
  #      - ./db/:/docker-entrypoint-initdb.d